FROM gradle:7.4.1 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build

FROM openjdk:8-jdk-alpine
EXPOSE 8080
ADD /home/gradle/src/build/libs/imedia24-coding-challenge-master.jar imedia24-coding-challenge-master.jar
ENTRYPOINT ["java", "-jar", "imedia24-coding-challenge-master.jar"]